# Deployment Web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaotemp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appconversaotemp
  template:
    metadata:
      labels:
        app: appconversaotemp
    spec:
      containers:
      - name: appconversaotemp
        image: elainecro/conversao-temperatura
        ports:
        - containerPort: 80
---
# Service app web
apiVersion: v1
kind: Service
metadata:
  name: conversaotemp
spec:
  selector:
    app: appconversaotemp
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30000
  type: NodePort